### PR TITLE
Added example Joystick and Encoder functions.

### PR DESCRIPTION
**Pull request by nicholastmosher**
So, you can view the code examples I wrote by clicking on the "commits" tab right above here.

I added a couple of functions that will help with what you wanted to do - pass IN joysticks and pass OUT encoders. To use these functions, you really should only need to call them each one time. When you're initializing your Robot.java (and after you've called your Drive myDrive = new Drive() constructor), you should be able to call setLeftJoystick() and setRightJoystick() which will then cause leftJoystick and rightJoystick INSIDE of your Drive.java to contain the proper joystick references, which you can then use. The same is true for getLeftEncoder and getRightEncoder. After you construct Drive(), you can 'get' the Encoders from Drive.java and use them in your Robot.java.

This is what's called a pull request. There should be an option nearby that says "merge pull request". If you do that, then all of the code changes that you see here will be applied into YOUR repository. You can do this if you want, or you can just choose to use this as a guideline to write your own code. It's up to you.

### CODE REVIEW

**Comment by MrBrenzozo** [comment]
when I build a method and use the return function, how do I return it to
iterative robot? I have all my subsytems as a subsystem class from
WPILib. Can a static variable from a subsystem class method be returned to
iterative robot?
Thanks for being the sounding board on this.

**Comment by MrBrenzozo** [comment]
Nick
I have the next 5 days off. Can we do a skype session in that time frame? I would like you to show me your methodology of building the subsystems and commands. If I draft a procedure to work it will help me avoid making mistakes. I am still pretty clumsy with just generating classes and methods. Thanks again. 
Sent from my Verizon Wireless BlackBerry

-----Original Message-----

**Comment by nicholastmosher** [comment]
I'd be glad to skype with you sometime this weekend. I have a few meetings
and things going on tomorrow morning and early afternoon, and I'm not sure
what will be going on the rest of the day, but Sunday seems to be a good
day if it works for you. I also think it might be a good opportunity to
record that call so that you can show it to Zach or future members of the
programming team. Let me know if that works for you!

**Comment by MrBrenzozo** [comment]
Sunday morning worKs great. What time?
Sent from my Verizon Wireless BlackBerry

-----Original Message-----

**Comment by MrBrenzozo** [comment]
How about 10:00?
Sent from my Verizon Wireless BlackBerry

-----Original Message-----

**Pull request merged**
